### PR TITLE
🐛 Unblock Service deletion when VirtualMachineService is not found

### LINKED ISSUE #1416: Load Balancer Service fails to delete after apply/delete the workload repeatedly
### What happened?

When apply/delete the workload repeatedly, there is a chance that the service is not deleted.

### What did you expect to happen?

CPI should be better handle the case.

### How can we reproduce it (as minimally and precisely as possible)?

Workload yaml windows-workload-svc.yaml
```
---
apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: win-webserver
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: win-webserver
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      tolerations:
        - key: os
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: windowswebserver
          image: mcr-docker-remote.artifactory.eng.vmware.com/windows/servercore:ltsc2022
          command:
            - powershell.exe
            - -command
            - "<#code used from https://gist.github.com/19WAS85/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
      nodeSelector:
        kubernetes.io/os: windows
```

Test script
```
#!/bin/bash

# Check for necessary arguments
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <yaml-file> <namespace> <iterations>"
    exit 1
fi

YAML_FILE="$1"
NAMESPACE="$2"
ITERATIONS="${3:-1}"  # Default to 1 iteration if not provided

# Function to check if all deployments are ready
wait_for_deployments() {
    echo "Waiting for all deployments in namespace '$NAMESPACE' to be ready..."

    # Get list of deployments in the namespace
    deployments=$(kubectl get deployments -n "$NAMESPACE" -o jsonpath='{.items[*].metadata.name}')

    for deployment in $deployments; do
        echo "Waiting for deployment '$deployment' to be ready..."
        kubectl rollout status deployment "$deployment" -n "$NAMESPACE"
        if [ $? -ne 0 ]; then
            echo "Deployment '$deployment' failed to become ready!"
            exit 1
        fi
    done

    echo "All deployments are ready!"
}

# Run the operation 'times' number of times
for ((i=1; i<=ITERATIONS; i++)); do
    echo "Iteration $i / $ITERATIONS"

    # Apply the YAML to the cluster
    echo "Applying resources from $YAML_FILE..."
    kubectl apply -f "$YAML_FILE" -n "$NAMESPACE"
    if [ $? -ne 0 ]; then
        echo "Failed to apply YAML to the cluster. Exiting..."
        exit 1
    fi

    # Wait for all deployments in the namespace to be ready
    wait_for_deployments

    # Delete resources defined in the YAML file
    echo "Deleting resources defined in $YAML_FILE..."
    kubectl delete -f "$YAML_FILE" -n "$NAMESPACE" --timeout 2m
    if [ $? -ne 0 ]; then
        echo "Failed to delete resources from the cluster. Exiting..."
        exit 1
    fi

    echo "Iteration $i completed!"
done

echo "All iterations completed successfully."
```

./attach-test.sh ./windows-workload-svc.yaml default 10

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

```
E0215 09:59:22.978484       1 controller.go:301] "Unhandled Error" err="error processing service default/win-webserver (retrying with exponential backoff): failed to check if load balancer exists before cleanup: VirtualMachineService not found"
I0215 09:59:22.979002       1 event.go:389] "Event occurred" object="default/win-webserver" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to check if load balancer exists before cleanup: VirtualMachineService not found"
E0215 09:59:54.481770       1 loadbalancer.go:72] failed to get load balancer for default/win-webserver: VirtualMachineService not found
E0215 09:59:54.486790       1 controller.go:301] "Unhandled Error" err="error processing service default/win-webserver (retrying with exponential backoff): failed to check if load balancer exists before cleanup: VirtualMachineService not found"
```

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.31.4+vmware.1-fips
```

</details>

### Cloud provider or hardware configuration

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Kernel (e.g. `uname -a`)

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

I believe the issue was contributed by the logic here https://github.com/kubernetes/cloud-provider-vsphere/blob/ed2b673aed34993ca545068dcb8cd9a3e9241631/pkg/cloudprovider/vsphereparavirtual/loadbalancer.go#L71-L74

<details>

</details>

### PR DESCRIPTION
**Pull request by zhanggbj**
**What this PR does / why we need it**:
Currently when virtualmachineservice is not found, an err is returned and cloud provider reports err and won't able to delete LB Service anymore. Actually CPI should return nil in this case.

https://github.com/kubernetes/cloud-provider/blob/master/controllers/service/controller.go#L378-L398

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1416

**Special notes for your reviewer**:

**Release note**:

```release-note
Unblock Service deletion when VirtualMachineService is not found
```

### CODE REVIEW

**Review by laozc — APPROVED** [review]
LGTM

File: pkg/cloudprovider/vsphereparavirtual/loadbalancer.go [hunk 1]
```diff
@@ -68,9 +68,11 @@ func (l *loadBalancer) GetLoadBalancer(ctx context.Context, clusterName string,
 		return nil, false, err
 	}
 
+	// When err is nil and vmService is nil, it indicates VirtualMachineService not found, but it's not an error.
+	// Return nil so that cloud provider could move on and delete the LB service.
 	if vmService == nil {
-		klog.Errorf("failed to get load balancer for %s: VirtualMachineService not found", namespacedName(service))
-		return nil, false, errors.Errorf("VirtualMachineService not found")
+		klog.V(1).Infof("VirtualMachineService not found %s", namespacedName(service))
```
Comment (DanielXiao) [inline pkg/cloudprovider/vsphereparavirtual/loadbalancer.go:74]: It is expected to return an error if VirtualMachineService not found. What 's the problem with LB service deletion?

Comment (zhanggbj) [reply pkg/cloudprovider/vsphereparavirtual/loadbalancer.go:74]: @DanielXiao 
This is called during LB Service deletion process, if underlying VM Service is not found, it is desired behavior, so it should return nil, so LB Service could continue the deletion process. Please refer to https://github.com/kubernetes/cloud-provider/blob/fd6122fdb023609bb07998141cc6cb039ab41ad5/controllers/service/controller.go#L374-L398.

If we return error for not found, LB Service will be blocked in deletion process.

Comment (zhanggbj) [reply pkg/cloudprovider/vsphereparavirtual/loadbalancer.go:74]: Reference from AWS implementation https://github.com/kubernetes/cloud-provider-aws/blob/e955e7686dd713acc5638c2a1f367d8c4ae3213e/pkg/providers/v1/aws.go#L2570-L2598

**Comment by zhanggbj** [comment]
Commit is verified on downstream env

To reproduce:
1. Create LB Service
2. Delete VM Service on supervisor
3. Try to delete LB Service, it will be blocked with error like "failed to check if load balancer exists before cleanup: VirtualMachineService not found"

With this commit, LB Service will be deleted successfully.
